# Generated by Django 2.0 on 2020-08-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('checksumhash', models.CharField(max_length=1000)),
                ('transtxn', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
    ]
