# Generated by Django 2.0 on 2020-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200806_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
