# Generated by Django 2.0 on 2020-08-10 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phoneverification', '0002_auto_20200810_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_verify',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
